"""add_python_parsed_value_to_evidence

Revision ID: 6f900ab3c42d
Revises: b31827dd6b79
Create Date: 2026-05-06 03:12:46.158478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f900ab3c42d'
down_revision: Union[str, Sequence[str], None] = 'b31827dd6b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_evidences', sa.Column('python_parsed_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_evidences', 'python_parsed_value')
    # ### end Alembic commands ###
