"""add_vendor_tender_link_and_evidence_table

Revision ID: b31827dd6b79
Revises: 30607da06071
Create Date: 2026-05-06 03:00:28.842540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b31827dd6b79'
down_revision: Union[str, Sequence[str], None] = '30607da06071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_evidences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('criterion_id', sa.String(), nullable=False),
    sa.Column('raw_string', sa.String(), nullable=False),
    sa.Column('context_sentence', sa.String(), nullable=False),
    sa.Column('llm_inferred_integer', sa.Integer(), nullable=True),
    sa.Column('contains_multiple_financial_entities', sa.Boolean(), nullable=True),
    sa.Column('source_chunk', sa.String(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('document_status', sa.String(), nullable=False),
    sa.Column('is_ambiguous', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['criterion_id'], ['criteria.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vendors', sa.Column('tender_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'vendors', 'tenders', ['tender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='foreignkey')
    op.drop_column('vendors', 'tender_id')
    op.drop_table('vendor_evidences')
    # ### end Alembic commands ###
